export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';
export const REMOVE_COMMENT_MESSAGE = 'REMOVE_COMMENT_MESSAGE';
export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_COMMENTS_THREAD = 'SET_COMMENTS_THREAD';
export const GET_COMMENTS = 'GET_COMMENTS';
export const EDIT_COMMENT = 'EDIT_COMMENTS';
